name: ccquant
version: "1.0.0"
config-version: 2

profile: ccquant

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  dbt_project_evaluator:
    primary_key_test_macros: [["dbt.test_unique", "dbt.test_not_null"], ["dbt_utils.test_unique_combination_of_columns"]]

models:
  ccquant:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
    signals:
      +materialized: table
      +schema: signals
    events:
      +materialized: table
      +schema: events
  dbt_project_evaluator:
    +enabled: true

seeds:
  ccquant:
    events:
      +schema: events
    symbol_chain_map:
      +schema: intermediate
